version: '3'
services:
   web:
       image: nginx:alpine
       volumes:
           - "./default.conf:/etc/nginx/conf.d/default.conf"
           - "./web:/web"
       ports:
           - "3000:80"
   php:
       image: php:7.2-fpm
       restart: always
       volumes:
           - "./default.conf:/etc/nginx/conf.d/default.conf"
           - "./web:/web"
   composer:
     restart: 'no'
     image: composer
     command: install
     volumes:
       - "./web:/app"